projects:
  minoritymarket:
    schemaPath: amplify/backend/api/minoritymarket/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-1
        apiId: null
        maxDepth: 2
