/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://n13ymupj66.execute-api.us-west-1.amazonaws.com/staging",
            "region": "us-west-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://vvvdngqynza63kkt2e6ww4cqhe.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jvfnatbwoffs3aft66hwkdr4oy",
    "aws_cognito_identity_pool_id": "us-west-1:780ca1c1-084b-489b-8759-83376c256840",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_cfBkptwe6",
    "aws_user_pools_web_client_id": "4ogo2qljebd015m0k3kogfh8o1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "minoritymarket-imagestore24817-staging",
    "aws_user_files_s3_bucket_region": "us-west-1",
    "geo": {
        "amazon_location_service": {
            "region": "us-west-2",
            "maps": {
                "items": {
                    "SearchMap-staging": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "SearchMap-staging"
            }
        }
    }
};


export default awsmobile;
